Set up
rpire/bookstore pull request #1
Opened 2021-09-27 19:32 UTC by rpire

## Changes made:
- Initialize `React` using `create-react-app`.
- Built skeleton components.
- Set up Linters in the repository.
- Added `Redux` folders and files to approach *Ducks* structure.
- Installed `React-Redux` in the repository.

2021-09-27 21:01 UTC, EricMbouwe requested changes
Hi @rpire,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-27 21:01 UTC, EricMbouwe commented on src/components/BookInput.js
> +    </form>
- [x] There is a field missing here, the `author input`. Each book has a `title` and `author` as well as a `category`, let's add that field to your form.
- [ OPTIONAL] Try to give a meaningful name to your component so that it becomes self-explanatory. As an example, you can use  `BookForm` or `CreateNewBook`

2021-09-27 21:01 UTC, EricMbouwe commented on src/components/List.js
> +);
- [x] Following the requirements this list should be populated with books using the `Book` component for each book.

- [x] I can notice that you have not implemented a Book component, as I have mentioned above it will be used to display a single book, it takes the book data as a prop and renders the title and the author, and has a button for removing the book (that wouldn't remove the books yet). Let's go ahead and create it.

2021-09-27 21:24 UTC, rpire commented
Hello, @EricMbouwe 👋

Thank you for reviewing my work. I will make sure to implement the requested changes before requesting another review. 🤓

Cheer and Happy Coding! 🚀

2021-09-27 22:08 UTC, rpire commented on src/components/BookInput.js
> +    </form>
Required changes fulfilled.

2021-09-27 22:09 UTC, rpire commented on src/components/List.js
> +);
Required changes fulfilled.

2021-09-27 22:29 UTC, GzimAsani approved these changes
# Hello @rpire       

## Thank you for implementing all the requirements asked previously. Your project is **ACCEPTED :green_circle:** and I wish you the best of luck in your next projects :+1: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-28 10:37 UTC, rpire commented
Hello @GzimAsani 👋

### Thank you 🙌

Thank you for reviewing my work. I will proceed to merge the changes into the `dev` branch. 🚀

Cheers! 🤓

2021-09-28 10:41 UTC, merged